# ğŸš€ AUTODESK INVENTOR

# Flanged Conical Support Pedestal â€” Autodesk Inventor CAD Model

## ğŸ“– Overview
This project models a flanged conical support pedestal with square base and central cylindrical protrusion, fully created in Autodesk Inventor. The component demonstrates key Inventor workflows: sketch-based extrusion, revolve for cylindrical and conical features, patterned holes, large fillet transitions, and precise dimension-driven modeling from an engineering drawing.

## ğŸ¯ Objective
Accurately recreate the support pedestal from the provided technical drawing while ensuring clean, parametric, manufacture-ready geometry suitable for machining, casting or 3D printing. Commonly used as an elevated base for pipes, shafts, rods or machinery components.

## âš™ï¸ Specifications & Commands

| **Design Specifications**          | **Autodesk Inventor Commands / Features Demonstrated** |
|------------------------------------|--------------------------------------------------------|
| Base: 80 Ã— 80 mm                   | Sketch â†’ Extrude                                       |
| Mounting holes: 4 Ã— Ã˜12 mm         | Hole â†’ Circular Pattern                                |
| Central boss Ã˜: 34 mm outer / 18 mm inner | Revolve                                         |
| Overall height: 40 mm              | Extrude / Revolve                                      |
| Base thickness: 10 mm              | Extrude                                                |
| Taper height: 37 mm                | Fillet (R20 mm)                                        |
| Large fillet: R20 mm               | Fillet tool                                            |
| Units: Millimeters (mm)            | Parametric dimensions & constraints                    |

## âœ¨ Design Features
- Square base with four corner mounting holes  
- Conical tapered transition body  
- Central cylindrical boss with through bore  
- Large R20 mm rounded base transitions  
- Uniform geometry suitable for casting/machining  

## ğŸ“ Technical Drawing Source
Model built directly from the provided 2D drawing:  
- Top view: 80 mm square, Ã˜34/Ã˜18 mm central features, four Ã˜12 mm holes  
- Front view: 40 mm height, 10 mm base, 37 mm taper, 5 mm top step  
- All dimensions and fillet callouts in mm  

## ğŸ“¸ Models / Screenshots

![Drawing View](FS0.jpeg)  
![3D Model View](FS1.png)  
![3D Model View](FS2.png)  
![3D Model View](FS3.png)

## ğŸ“¥ CAD Downloads

[Download archive](./Flanged%20Support.zip)  


## ğŸ­Manufacturing Considerations

Recommended methods:
- CNC machining (aluminum/steel)  
- Sand/investment casting + finish machining  
- 3D printing (prototypes)  

Supports:  
- M10â€“M12 bolts through Ã˜12 mm holes  
- Large R20 fillets for stress relief & deburring  

## ğŸŒ Applications
- Pipe/tube support stands  
- Shaft/rod pedestals  
- Machinery alignment bases  
- Equipment mounting supports  

## ğŸ’­ Reflection
This Inventor project demonstrated:

- Interpreting multiview drawings  
- Revolve & extrusion for cylindrical/conical geometry  
- Fully constrained parametric sketches  
- Large fillets for production-ready parts  
- Clean model for drawings/assemblies/CAM  

Possible enhancements:  
- Add bolt features  
- Create annotated drawing sheet  
- Assign material & mass  
- Basic stress simulation  
- Small assembly with sample component  

Feedback welcome! ğŸ’¬
